-- Enable TimescaleDB and UUID extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;

-- 1. Human User Profiles (id matches auth.users.id generated by Supabase Auth)
CREATE TABLE IF NOT EXISTS profiles (
    id UUID PRIMARY KEY,
    full_name TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 2. Gateways & Authorization
CREATE TABLE IF NOT EXISTS gateways (
    gateway_id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS user_gateways (
    user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    gateway_id TEXT REFERENCES gateways(gateway_id) ON DELETE CASCADE,
    role TEXT NOT NULL DEFAULT 'viewer',
    created_at TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY (user_id, gateway_id)
);

-- 3. Sensors
CREATE TABLE IF NOT EXISTS sensors (
    sensor_id TEXT NOT NULL,
    gateway_id TEXT REFERENCES gateways(gateway_id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    unit TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY (gateway_id, sensor_id)
);

-- 4. Message Deduplication & Outbox Tracking
CREATE TABLE IF NOT EXISTS processed_messages (
    gateway_id TEXT NOT NULL,
    message_id UUID NOT NULL,
    payload_hash TEXT NOT NULL,
    processed_at TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY (gateway_id, message_id)
);

-- 5. Telemetry Time-Series (TimescaleDB Hypertable)
CREATE TABLE IF NOT EXISTS telemetry (
    measured_at TIMESTAMPTZ NOT NULL,
    gateway_id TEXT NOT NULL,
    sensor_id TEXT NOT NULL,
    sequence_num BIGINT NOT NULL,
    value DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (measured_at, gateway_id, sensor_id, sequence_num)
);

-- Turn telemetry into TimescaleDB Hypertable with 1-day chunk interval
SELECT create_hypertable(
    'telemetry',
    'measured_at',
    chunk_time_interval => INTERVAL '1 day',
    if_not_exists => TRUE
);

-- Create secondary index for sensor-specific historical range queries
CREATE INDEX IF NOT EXISTS idx_telemetry_gateway_sensor_time 
ON telemetry (gateway_id, sensor_id, measured_at DESC);

-- Enable TimescaleDB Columnar Compression
ALTER TABLE telemetry SET (
    timescaledb.compress,
    timescaledb.compress_segmentby = 'gateway_id, sensor_id',
    timescaledb.compress_orderby = 'measured_at DESC, sequence_num DESC'
);

-- Automatically compress chunks older than 7 days
SELECT add_compression_policy('telemetry', INTERVAL '7 days', if_not_exists => TRUE);

-- Automatically drop raw chunks older than 30 days (Retention policy)
SELECT add_retention_policy('telemetry', INTERVAL '30 days', if_not_exists => TRUE);

-- 6. Media Objects (Images/Files uploaded to Supabase Storage)
CREATE TABLE IF NOT EXISTS media_objects (
    media_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    gateway_id TEXT REFERENCES gateways(gateway_id) ON DELETE CASCADE,
    storage_path TEXT NOT NULL,
    media_type TEXT NOT NULL,
    expected_size BIGINT,
    actual_size BIGINT,
    checksum TEXT,
    validation_status TEXT DEFAULT 'pending',
    created_at TIMESTAMPTZ DEFAULT now()
);
