run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - revive
    - misspell

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: iot-platform
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
      - name: blank-imports
      - name: context-as-argument
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0